package com.redoc.idu.model.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORY".
 */
public class Category {

    private Long id;
    /** Not-null value. */
    private String CATEGORY_NAME;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String CATEGORY_NAME) {
        this.id = id;
        this.CATEGORY_NAME = CATEGORY_NAME;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCATEGORY_NAME() {
        return CATEGORY_NAME;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCATEGORY_NAME(String CATEGORY_NAME) {
        this.CATEGORY_NAME = CATEGORY_NAME;
    }

}
