package com.redoc.idu.model.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHANNEL".
 */
public class Channel {

    private Long id;
    private String CHANNEL_ID;
    private String CHANNEL_NAME;
    private String CATEGORY_ID;
    private Boolean CAN_CACHE;
    private Boolean FOLLOWED;
    private String LINK;
    private Integer WEIGHT;

    public Channel() {
    }

    public Channel(Long id) {
        this.id = id;
    }

    public Channel(Long id, String CHANNEL_ID, String CHANNEL_NAME, String CATEGORY_ID, Boolean CAN_CACHE, Boolean FOLLOWED, String LINK, Integer WEIGHT) {
        this.id = id;
        this.CHANNEL_ID = CHANNEL_ID;
        this.CHANNEL_NAME = CHANNEL_NAME;
        this.CATEGORY_ID = CATEGORY_ID;
        this.CAN_CACHE = CAN_CACHE;
        this.FOLLOWED = FOLLOWED;
        this.LINK = LINK;
        this.WEIGHT = WEIGHT;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCHANNEL_ID() {
        return CHANNEL_ID;
    }

    public void setCHANNEL_ID(String CHANNEL_ID) {
        this.CHANNEL_ID = CHANNEL_ID;
    }

    public String getCHANNEL_NAME() {
        return CHANNEL_NAME;
    }

    public void setCHANNEL_NAME(String CHANNEL_NAME) {
        this.CHANNEL_NAME = CHANNEL_NAME;
    }

    public String getCATEGORY_ID() {
        return CATEGORY_ID;
    }

    public void setCATEGORY_ID(String CATEGORY_ID) {
        this.CATEGORY_ID = CATEGORY_ID;
    }

    public Boolean getCAN_CACHE() {
        return CAN_CACHE;
    }

    public void setCAN_CACHE(Boolean CAN_CACHE) {
        this.CAN_CACHE = CAN_CACHE;
    }

    public Boolean getFOLLOWED() {
        return FOLLOWED;
    }

    public void setFOLLOWED(Boolean FOLLOWED) {
        this.FOLLOWED = FOLLOWED;
    }

    public String getLINK() {
        return LINK;
    }

    public void setLINK(String LINK) {
        this.LINK = LINK;
    }

    public Integer getWEIGHT() {
        return WEIGHT;
    }

    public void setWEIGHT(Integer WEIGHT) {
        this.WEIGHT = WEIGHT;
    }

}
